### ISSUE TITLE
[review] 현재까지 코드 리뷰

### ISSUE THREAD

**Issue by annapo99** [TEAM-ALOM/study-swiftui-sori#7]
(이거 읽고 나서 지워주시면 됩니다.)

## 뷰 분리에 대한 고민

```swift
struct ContentView: View {
    var body: some View {
        VStack(alignment: .leading, spacing: 5) {
            VStack {
                SearchView()
                TransportationView()
            }
            OnlyUseView()
            SortView()
            RouteView()
        }
        .padding(/*@START_MENU_TOKEN@*/.horizontal/*@END_MENU_TOKEN@*/)
    }
}
```
뷰를 분리하는 것은 아주 좋은 습관이라고 생각해요. 
뷰를 언제 분리하는게 좋을까에 대한 논의는 많지만, 정답은 없고 제가 여러 코드를 보면서 느낀점을 정리해보겠습니다.

첫번째, 같은 뷰가 여러번 쓰일때. 재사용성을 높이기 위해서 뷰를 분리하는게 좋아보여요. 특히 리스트안에 들어가는 아이템들은 여러번 재사용되기 때문에 분리하는게 좋아보여요. 그래서 제 생각에는 ContentView 안에 ResultView를 넣어주고, ResultView안에 모든 View들을 집어넣는 방식을 추천드립니다. ContentView는 MainView에서 실행되는 거의 Root 급의 View이기 때문에 탭바관련된 뷰들을 넣어주는 게 좋아보여요. 예를 들면 지금은 ResultView 하나지만, 주변, 저장, 대중교통, 네비게이션, 마이페이지 뷰를 넣어주는 곳이 ContentView가 될거에요.

두번째, 너무 복잡할때. 뷰가 너무 복잡한 경우가 분명히 존재해요. 이거를 안묶어주면 가독성이 매우 떨어지는 경우가 있습니다. 분명 여기 페이지에서 단 한번만 쓰일 뷰이지만, 이럴때에는 뷰를 분리해주는 게 좋아요. 

세번째, 나중에 확장 가능성을 염두해 두고 짜는 경우. 이 뷰는 언젠가 다시한번 쓰일 거야 하도록 작성하는 경우가 있어요. 한번만 쓰이게 뷰를 작성하는 것보다는 확장 가능성을 염두해 두고 짜는 습관이 좋아요..

주석달아주셔서 어디서 고민하셨는지 확인이 되네요 .. ! 다음부터는 PR 날려주시면 그때 코드 하나씩 살펴보겠슴니다 !

**Comment by thissound22** [comment]
감사합니다!! 혹시 안 지워도 되는 건가요?

**Comment by thissound22** [comment]
그리고 말씀하신 ResultView가 추후에 저장, 마이페이지 등 뷰를 추가하였을 경우를 염두하고 지금 현재 구성하고 있는 뷰의 네임을 가리키는 건가요!?

**Comment by annapo99** [comment]
네네 말씀하신대로 이해한게 맞아요. 

ContentView가 지금 하나의 뷰로 사용되고 있는데, 이것보다 ResultView로 한번 감싸서 관리하는것을 의미했습니다. 
이슈는 지워도 되고 안지워도 되는데, close 이슈 버튼을 누르시면 이슈가 closed 탭으로 넘어갑니다.

**Comment by thissound22** [comment]
아아 넵!! 감사합니다!
